export const SKILLS = [
  { cat:{en:'Frontend',de:'Frontend'}, items:['JavaScript ES6+','React.js','React Native','Redux','HTML5','CSS3','Tailwind CSS','Bootstrap','Material UI','Styled-Components'] },
  { cat:{en:'Backend',de:'Backend'}, items:['Node.js','Express.js','MongoDB','REST APIs'] },
  { cat:{en:'Tools & Deploy',de:'Werkzeuge & Deployment'}, items:['Git','GitHub','Vercel','Netlify','Render','Heroku','Cloudinary','Expo'] },
  { cat:{en:'Design / UX',de:'Design / UX'}, items:['Figma','FigJam','Maze','Jira','Design Thinking','Wireframing','Prototyping'] },
];

export const EXP = [
  {
    co:'EMRAN', full:'Exxonmobil Retirees Association of Nigeria',
    role:{en:'Lead Full-Stack Developer & Technical Support',de:'Leitender Full-Stack-Entwickler & Technischer Support'},
    loc:'Remote', period:'Oct 2025 – Present', col:'#63b3ed',
    pts:{
      en:['Lead developer for a full-scale membership platform serving 500+ former ExxonMobil Nigeria employees','Built member portal and secure admin portal with role-based access control (super-admin / admin)','Features: pension & medical management, insurance, elections, events, dues & registration fee payments','Integrated secure authentication & authorisation with protected routes and session management','Built payment gateway for member dues collection','Admin portal exclusively accessible to admins provisioned by a super-admin'],
      de:['Leitender Entwickler einer Mitgliederplattform für 500+ ehemalige ExxonMobil-Nigeria-Mitarbeiter','Mitgliederportal und gesichertes Adminportal mit rollenbasierter Zugriffskontrolle','Funktionen: Renten- & Krankenversicherungsverwaltung, Wahlen, Veranstaltungen, Jahresbeiträge','Sicheres Authentifizierungs- & Autorisierungssystem mit geschützten Routen','Zahlungs-Gateway für die Beitragseinzahlung','Adminportal ausschließlich für von einem Super-Admin bereitgestellte Administratoren'],
    },
    links:[{t:'emran.center',u:'https://emran.center'},{t:'Admin Portal',u:'https://emran-admin.vercel.app'}],
  },
  {
    co:'Campusify', full:'Campusify Enterprise',
    role:{en:'Founder & Full-Stack Developer',de:'Gründer & Full-Stack-Entwickler'},
    loc:'Lagos, Nigeria', period:'Feb 2024 – Oct 2025', col:'#f6ad55',
    pts:{
      en:['Sole full-stack developer — architecture, development, and deployment of a B2B student commerce platform','Built responsive web app using React, Node.js, MongoDB and Cloudinary','Developed and published Android app using Expo and React Native with Google AdMob and Unity Ads','Delivered mobile-first UI achieving full cross-device compatibility'],
      de:['Alleiniger Full-Stack-Entwickler — Architektur, Entwicklung und Deployment einer B2B-Handelsplattform','Entwicklung der responsiven Web-App mit React, Node.js, MongoDB und Cloudinary','Veröffentlichung der Android-App mit Expo und React Native inkl. AdMob und Unity Ads','Vollständige Cross-Device-Kompatibilität durch Mobile-First-Entwicklung'],
    },
    links:[{t:'campusify.net',u:'https://campusify.net'},{t:'Play Store',u:'https://play.google.com/store/apps/details?id=com.bootstrap131.appcampusify'}],
  },
  {
    co:'Estility', full:'Estility Inc.',
    role:{en:'Junior Frontend Developer',de:'Junior Frontend-Entwickler'},
    loc:'Nigeria · Remote', period:'Jan 2022 – Aug 2022', col:'#b794f4',
    pts:{
      en:['Designed scalable, responsive interfaces using React.js, Redux and Tailwind CSS','Converted Figma mockups into pixel-perfect HTML & CSS components','Collaborated in a distributed remote team via GitHub, code reviews and daily standups'],
      de:['Entwicklung skalierbarer, responsiver Benutzeroberflächen mit React.js, Redux und Tailwind CSS','Pixel-genaue Umsetzung von Figma-Designs in HTML & CSS','Zusammenarbeit im Remote-Team über GitHub, Code-Reviews und Standups'],
    },
    links:[],
  },
  {
    co:"Int'l Breweries", full:'International Breweries',
    role:{en:'Condition Monitoring Engineer (NYSC)',de:'Ingenieur für Zustandsdiagnose (NYSC)'},
    loc:'Onitsha, Anambra', period:'Jan 2020 – Dec 2021', col:'#68d391',
    pts:{
      en:['Monitored hundreds of motors, pumps, gearboxes and electrical breakers','Conducted Thermography, Oil and Vibration Analysis for predictive maintenance','Compiled and defended technical condition reports for plant machinery'],
      de:['Überwachung von Motoren, Pumpen, Getrieben und Schaltern','Thermografie-, Öl- und Vibrationsanalyse zur vorausschauenden Instandhaltung','Erstellung und Verteidigung technischer Zustandsberichte'],
    },
    links:[],
  },
  {
    co:'Fogaecelectro', full:'Fogaecelectrophysics',
    role:{en:'Technical Customer Support Specialist',de:'Technischer Kundendienst'},
    loc:'Texas, USA · Remote', period:'Sep 2017 – Oct 2019', col:'#fc8181',
    pts:{
      en:['Managed client database records and prepared bug reports and technical documentation','Assisted clients with environment setup and resolved technical issues'],
      de:['Verwaltung von Kundendatenbanken sowie Erstellung von Fehlerberichten','Unterstützung beim Einrichten der Arbeitsumgebung und Lösung technischer Probleme'],
    },
    links:[],
  },
];

export const PROJECTS = [
  { name:'EMRAN Platform', icon:'🏛️', badge:'Live · 2025', bc:'#63b3ed',
    sub:{en:'Exxonmobil Retirees Association of Nigeria',de:'Exxonmobil-Rentnerverband Nigeria'},
    stack:['React','Node.js','MongoDB','Express','Cloudinary','JWT'],
    desc:{en:'Full-scale membership platform for 500+ former ExxonMobil Nigeria employees. Pension & medical management, insurance, elections, events, dues payments, auth & hardened admin portal.',de:'Vollständige Mitgliederplattform für 500+ ehemalige ExxonMobil-Mitarbeiter. Renten- & Krankenversicherung, Wahlen, Veranstaltungen, Beitragszahlungen und gesichertes Adminportal.'},
    links:[{t:'emran.center ↗',u:'https://emran.center'},{t:'Admin Portal ↗',u:'https://emran-admin.vercel.app'}],
    acc:'rgba(99,179,237,.08)' },
  { name:'Campusify Web', icon:'🎓', badge:'Live · 2024', bc:'#f6ad55',
    sub:{en:'B2B Student Commerce Platform',de:'B2B-Handelsplattform für Studierende'},
    stack:['React','Node.js','MongoDB','Express','Cloudinary','Redux'],
    desc:{en:'End-to-end B2B student commerce platform. Full technical ownership — frontend, backend API, database design, and cloud media.',de:'Vollständige B2B-Handelsplattform. Eigenständig entwickelt — Frontend, Backend-API, Datenbankdesign und Cloud-Medien.'},
    links:[{t:'campusify.net ↗',u:'https://campusify.net'}],
    acc:'rgba(246,173,85,.07)' },
  { name:'Campusify Android', icon:'📱', badge:'Published', bc:'#68d391',
    sub:{en:'Mobile Commerce App',de:'Mobile Commerce App'},
    stack:['React Native','Expo','AdMob','Unity Ads'],
    desc:{en:'Native Android companion to Campusify with ad monetisation via Google AdMob and Unity Ads. iOS in development.',de:'Native Android-Begleit-App zu Campusify mit Werbemonetarisierung. iOS-Version in Entwicklung.'},
    links:[{t:'Google Play ↗',u:'https://play.google.com/store/apps/details?id=com.bootstrap131.appcampusify'}],
    acc:'rgba(104,211,145,.07)' },
  { name:'Plurity Plumbing', icon:'🔧', badge:'Live', bc:'#b794f4',
    sub:{en:'Business Website',de:'Unternehmenswebsite'},
    stack:['React','Tailwind CSS','Bootstrap','Cloudinary'],
    desc:{en:'Professional website for a plumbing services sole proprietorship. Fully responsive with cloud-hosted media.',de:'Professionelle Website für ein Klempnereiunternehmen. Vollständig responsiv mit Cloud-Medien.'},
    links:[{t:'plurityplumbingsolutions.com ↗',u:'https://www.plurityplumbingsolutions.com/'}],
    acc:'rgba(183,148,244,.07)' },
  { name:'Catalogue A', icon:'📋', badge:'Live', bc:'#fc8181',
    sub:{en:'Invitation Web App',de:'Einladungs-Web-App'},
    stack:['React','Firebase','Google Sheets API'],
    desc:{en:'Invitation management app that captures user invites and syncs to a Google Spreadsheet via Firebase.',de:'Einladungsmanagement-App, die Nutzereinladungen via Firebase mit Google Sheets synchronisiert.'},
    links:[{t:'cataloguea.vercel.app ↗',u:'https://cataloguea.vercel.app/'}],
    acc:'rgba(252,129,129,.07)' },
];

export const EDU = [
  { icon:'🎨', ea:'rgba(246,173,85,.12)', school:'Aceplora Coding Academy', period:'Apr 2023 – Aug 2023',
    deg:{en:'Remote UI/UX Product Design · 500+ hours',de:'Remote UI/UX Produktdesign · 500+ Stunden'},
    det:{en:'Design Thinking, User Flows, Wireframing, Prototype Design, Empathy & Affinity Mapping. Figma, FigJam, Maze, Jira.',de:'Design Thinking, User Flows, Wireframing, Prototyping, Empathy Maps. Figma, FigJam, Maze, Jira.'} },
  { icon:'💻', ea:'rgba(99,179,237,.12)', school:'Codecademy.com', period:'Feb 2022 – Nov 2022',
    deg:{en:'Full-Stack Web Development · 1,300+ hours',de:'Full-Stack-Webentwicklung · 1.300+ Stunden'},
    det:{en:'Algorithms, data structures, JavaScript, React, Redux, Ruby and Rails. Remote pair-programming via GitHub.',de:'Algorithmen, Datenstrukturen, JavaScript, React, Redux, Ruby und Rails. Remote Pair-Programming.'} },
  { icon:'🎓', ea:'rgba(183,148,244,.12)', school:'University of Benin', period:'Jan 2014 – Dec 2018',
    deg:{en:'B.A. International Studies & Diplomacy',de:'B.A. Internationale Studien & Diplomatie'},
    det:{en:'Modern International Relations · Diplomatic Relations · International Law · Collective Security.',de:'Moderne Internationale Beziehungen · Diplomatische Beziehungen · Völkerrecht · Kollektive Sicherheit.'} },
];

export const T = {
  en:{
    nav_skills:'Skills',nav_exp:'Experience',nav_proj:'Projects',nav_edu:'Education',nav_contact:'Contact',nav_hire:'Hire Me ✉',
    h_eye:'Available for opportunities',
    h_desc:'I build fast, scalable, beautiful applications — from database architecture to polished UI. Based in Lagos, open to remote and relocation.',
    h_cta1:'View My Work →',h_cta2:'Hire Me ✉',
    sk_tag:'Capabilities',sk_title:'Technical Skills',
    ex_tag:'Career',ex_title:'Work Experience',
    pj_tag:'Portfolio',pj_title:'Featured Projects',
    ed_tag:'Background',ed_title:'Education & Training',
    hi_tag:'Get in Touch',hi_title:"Let's Build Something Great",
    hi_sub:"Open to full-time roles, freelance projects, and contract work. Drop me a message and I'll get back to you within 24 hours.",
    f_name:'Your Name',f_email:'Email Address',f_subj:'Subject',f_msg:'Message',f_send:'Send Message →',
    hi_or:'— or reach me directly —',
    ct_title:'Open to Opportunities',
    ct_desc:'Based in Lagos, Nigeria. Available for remote work worldwide and open to relocation.',
    cp_ft:'Full-time',cp_fl:'Freelance',cp_ct:'Contract',cp_rm:'Remote',cp_rl:'Relocation',
    ct_ph:'Phone',ct_em:'Email',
    modal_ok_title:'Message Sent!',modal_ok_msg:"Thanks — I'll get back to you within 24 hours.",modal_ok_btn:'Got it',
    modal_fail_title:'Something went wrong',modal_fail_msg:'Failed to send. Please email louisjoseph131@gmail.com directly.',modal_fail_btn:'Try again',
  },
  de:{
    nav_skills:'Fähigkeiten',nav_exp:'Erfahrung',nav_proj:'Projekte',nav_edu:'Ausbildung',nav_contact:'Kontakt',nav_hire:'Kontaktiere mich ✉',
    h_eye:'Offen für neue Möglichkeiten',
    h_desc:'Ich entwickle schnelle, skalierbare Anwendungen — von der Datenbankarchitektur bis zur polierten Benutzeroberfläche. Standort Lagos, offen für Remote und Umzug.',
    h_cta1:'Meine Arbeit ansehen →',h_cta2:'Kontaktiere mich ✉',
    sk_tag:'Kompetenzen',sk_title:'Technische Fähigkeiten',
    ex_tag:'Karriere',ex_title:'Berufliche Erfahrung',
    pj_tag:'Portfolio',pj_title:'Ausgewählte Projekte',
    ed_tag:'Hintergrund',ed_title:'Ausbildung & Weiterbildung',
    hi_tag:'Kontakt aufnehmen',hi_title:'Lass uns etwas Großartiges bauen',
    hi_sub:'Ich bin offen für Festanstellungen, Freelance-Projekte und Auftragsarbeit. Schreib mir — ich melde mich innerhalb von 24 Stunden.',
    f_name:'Ihr Name',f_email:'E-Mail-Adresse',f_subj:'Betreff',f_msg:'Nachricht',f_send:'Nachricht senden →',
    hi_or:'— oder direkt kontaktieren —',
    ct_title:'Offen für Möglichkeiten',
    ct_desc:'Standort Lagos, Nigeria. Verfügbar für Remote-Arbeit weltweit, offen für Umzug.',
    cp_ft:'Festanstellung',cp_fl:'Freelance',cp_ct:'Auftrag',cp_rm:'Remote',cp_rl:'Umzug',
    ct_ph:'Telefon',ct_em:'E-Mail',
    modal_ok_title:'Nachricht gesendet!',modal_ok_msg:'Danke — ich melde mich innerhalb von 24 Stunden.',modal_ok_btn:'Verstanden',
    modal_fail_title:'Etwas ist schiefgelaufen',modal_fail_msg:'Nachricht konnte nicht gesendet werden. Bitte direkt an louisjoseph131@gmail.com schreiben.',modal_fail_btn:'Erneut versuchen',
  },
};
